# $Id$

MK = ../../mk
SRC = ../../src

LIB = libgreat_c99

TARGETS = wrap.o stdlib_prng.o stdlib_memory.o stdio_fileaccess.o ctype.o

all: $(LIB).so $(LIB).a

include $(MK)/cc.mk
include $(MK)/rules.mk
include $(MK)/lib.mk
include $(MK)/ar.mk

