# $Id$

MK = ../../mk
SRC = ../../src

LIB = libgreat_c89

TARGETS = wrap.o stdlib_memory.o

all: $(LIB).so $(LIB).a

include $(MK)/cc.mk
include $(MK)/rules.mk
include $(MK)/lib.mk
include $(MK)/ar.mk

