# $Id$

MK = ../../mk
SRC = ../../src

LIB = libgreat_bsd42

TARGETS = wrap.o sys_time.o

all: $(LIB).so $(LIB).a

include $(MK)/cc.mk
include $(MK)/rules.mk
include $(MK)/lib.mk
include $(MK)/ar.mk

